controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

unfold_controllers:
    resource:
        path: ../src/UnfoldBundle/Controller/
        namespace: App\UnfoldBundle\Controller
    type: attribute

